### ISSUE TITLE
Incompatible version of Django in Dockerfile

### ISSUE THREAD

**Issue by wagamama** [jsleetw/petneed.me#12]
The version of Django in Dockerfile is set to 1.4.3.
However, this version is incompatible with Django version in requirements.txt.
By using 1.4.3, following error occurs:

```
Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x1a264d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 91, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/petneed.me/pets/animal/models.py", line 3, in <module>
    from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
ImportError: cannot import name AbstractBaseUser
```

After changing to 1.5.3 that is same version in requirements.txt, the problem is solved.

**Comment by wagamama** [comment]
Fix in 407d2ce
